#!/usr/bin/env node
// Inlines the overlay HTML into a TS module so a single-file executable
// (bun build --compile) has no sibling files to read at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const serverDir = join(root, "src", "server");

const assets = {
  WHEEL_HTML: "wheel.html",
  HISTORY_HTML: "history.html",
};

const parts = [
  "// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.",
  `// Source: ${Object.values(assets).map((f) => `src/server/${f}`).join(", ")}`,
  "",
];

for (const [name, file] of Object.entries(assets)) {
  const html = readFileSync(join(serverDir, file), "utf-8");
  parts.push(`export const ${name}: string = ${JSON.stringify(html)};`, "");
}

const out = join(serverDir, "assets.generated.ts");
writeFileSync(out, parts.join("\n"), "utf-8");
console.log(`[gen-assets] Wrote ${out} (${Object.keys(assets).length} assets)`);
